### ISSUE TITLE
Template Repository機能のご提案

### ISSUE THREAD

**Issue by xhiroga** [catnose99/team-blog-hub#25]
GitHubでは、コミット履歴を共有しないでリポジトリの内容を複製できるテンプレート機能が利用できます。

[テンプレートリポジトリを作成する \- GitHub Docs](https://docs.github.com/ja/repositories/creating-and-managing-repositories/creating-a-template-repository)

使ってみたところ、コミット履歴が共有されていないので複製元に対してPRを出してしまう、という事故が防げそうでした。

![image](https://user-images.githubusercontent.com/13391129/147872788-de02dc55-1739-4673-bbe3-ef7e0c5d5770.png)
（PR作成時に対象リポジトリを選択できないスクショです）

また、テンプレート機能はオン・オフをいつでも切り替えることができます。

私のみならず複数の方が誤って本リポジトリにPRを出されているようなので、試しに本リポジトリをテンプレート化してみるのはいかがでしょうか。ご検討、よろしくお願いいたします。

**Comment by catnose99** [comment]
ご提案ありがとうございます！
仰る通りですね。さきほどテンプレートリポジトリへと変更しました。
